version: '3'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - '3000:80'
    volumes:
      - ./client:/app
    restart: always
